language: cpp

compiler:
  - clang
  - gcc

env:
  - SANITIZER=
  - SANITIZER=-fsanitize=thread

matrix:
  exclude:
    - compiler: gcc
      env: SANITIZER=-fsanitize=thread

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq g++-4.8
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
             -DCMAKE_CXX_FLAGS=$SANITIZER
             -DCMAKE_EXE_LINKER_FLAGS=$SANITIZER

script:
  - "make"
  - "ctest --output-on-failure"
