language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode8
      env:
        - SANITIZER=
    - os: osx
      osx_image: xcode8
      env:
        - SANITIZER=-fsanitize=thread
    - os: osx
      osx_image: xcode9
      env:
        - SANITIZER=
    - os: osx
      osx_image: xcode9
      env:
        - SANITIZER=-fsanitize=thread
    - os: linux
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
         - SANITIZER=
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
         - SANITIZER=
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
        - SANITIZER=
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - SANITIZER=

before_install:
    - eval "${MATRIX_EVAL}"

before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
             -DCMAKE_CXX_FLAGS=$SANITIZER
             -DCMAKE_EXE_LINKER_FLAGS=$SANITIZER

script:
  - make
  - ctest --output-on-failure
